import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, FileText, ExternalLink } from 'lucide-react'
import { fetchCaseAnnotations, type Annotation } from '@/lib/api'

/**
 * Source annotations for a patient: GDC administrative/QC notes plus any published
 * spatial annotations. Nothing here is generated by this project — every row shows the
 * collection it came from and whether a person or an algorithm produced it.
 */

// Presentation grouping over the source's own categories. The source never assigns a
// severity, so neither do we: these colours mark *what kind of flag* it is, not how bad.
const FLAG_STYLES: Record<string, { label: string; className: string }> = {
  dnu: { label: 'Do not use', className: 'bg-rose-100 text-rose-900 border-rose-300' },
  redaction: { label: 'Redaction / withdrawal', className: 'bg-purple-100 text-purple-900 border-purple-300' },
  qc_failure: { label: 'QC failure', className: 'bg-orange-100 text-orange-900 border-orange-300' },
  noncanonical: { label: 'Noncanonical item', className: 'bg-sky-100 text-sky-900 border-sky-300' },
  prior_malignancy: { label: 'Prior/synchronous malignancy', className: 'bg-teal-100 text-teal-900 border-teal-300' },
}

const FLAG_ORDER = ['dnu', 'redaction', 'qc_failure', 'noncanonical', 'prior_malignancy']

export default function AnnotationPanel({ caseId }: { caseId: string }) {
  const [rows, setRows] = useState<Annotation[] | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [flag, setFlag] = useState<string>('all')

  useEffect(() => {
    let cancelled = false
    setRows(null)
    setError(null)
    fetchCaseAnnotations(caseId)
      .then((r) => !cancelled && setRows(r.annotations))
      .catch((e) => !cancelled && setError(e instanceof Error ? e.message : 'Could not load annotations'))
    return () => {
      cancelled = true
    }
  }, [caseId])

  const counts = useMemo(() => {
    const c: Record<string, number> = {}
    for (const r of rows ?? []) if (r.flag_group) c[r.flag_group] = (c[r.flag_group] ?? 0) + 1
    return c
  }, [rows])

  const filtered = useMemo(
    () => (rows ?? []).filter((r) => flag === 'all' || r.flag_group === flag),
    [rows, flag],
  )

  if (error) {
    return <p className="text-sm text-red-600">{error}</p>
  }
  if (rows === null) {
    return <p className="text-sm text-muted-foreground">Loading annotations…</p>
  }
  if (rows.length === 0) {
    return (
      <p className="text-sm text-muted-foreground">
        No annotations are recorded against this patient in any imported collection.
      </p>
    )
  }

  const spatial = rows.filter((r) => r.is_spatial)
  const nonSpatial = rows.filter((r) => !r.is_spatial)

  return (
    <div className="space-y-3">
      <p className="text-xs text-muted-foreground">
        {rows.length} annotation{rows.length === 1 ? '' : 's'} · {nonSpatial.length} non-spatial ·{' '}
        {spatial.length} spatial. Every record comes from the collection shown in its Source column.
      </p>

      {Object.keys(counts).length > 0 && (
        <div className="flex flex-wrap items-center gap-1.5">
          <FilterChip active={flag === 'all'} onClick={() => setFlag('all')}>
            All ({rows.length})
          </FilterChip>
          {FLAG_ORDER.filter((g) => counts[g]).map((g) => (
            <FilterChip key={g} active={flag === g} onClick={() => setFlag(g)} className={FLAG_STYLES[g].className}>
              {FLAG_STYLES[g].label} ({counts[g]})
            </FilterChip>
          ))}
        </div>
      )}

      {counts.dnu > 0 && (
        <div className="flex items-start gap-2 rounded-md border border-rose-300 bg-rose-50 p-2.5 text-xs text-rose-900">
          <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
          <p>
            The source flagged {counts.dnu} item{counts.dnu === 1 ? '' : 's'} for this patient as
            <span className="font-semibold"> “Item flagged DNU”</span> (do not use). Consider excluding
            this patient from analyses that depend on the affected entities.
          </p>
        </div>
      )}

      <div className="overflow-auto max-h-[22rem] rounded-lg border">
        <table className="w-full text-sm">
          <thead className="bg-brand text-white sticky top-0 z-10">
            <tr>
              <th className="text-left font-semibold px-3 py-2.5">Category</th>
              <th className="text-left font-semibold px-3 py-2.5">Classification</th>
              <th className="text-left font-semibold px-3 py-2.5">Source entity</th>
              <th className="text-left font-semibold px-3 py-2.5">Notes</th>
              <th className="text-left font-semibold px-3 py-2.5">Source</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((a, i) => (
              <tr key={a.annotation_id} className={i % 2 === 0 ? 'bg-card' : 'bg-muted/40'}>
                <td className="px-3 py-2 align-top">
                  <div className="flex flex-col gap-1">
                    <span>{a.category || a.label || '—'}</span>
                    <div className="flex flex-wrap gap-1">
                      {a.flag_group && (
                        <span className={`text-[10px] px-1.5 py-0.5 rounded border ${FLAG_STYLES[a.flag_group].className}`}>
                          {FLAG_STYLES[a.flag_group].label}
                        </span>
                      )}
                      <span className="text-[10px] px-1.5 py-0.5 rounded border bg-slate-100 text-slate-700 border-slate-300">
                        {a.is_spatial ? `spatial · ${a.scope}` : 'non-spatial'}
                      </span>
                    </div>
                  </div>
                </td>
                <td className="px-3 py-2 align-top">{a.classification || '—'}</td>
                <td className="px-3 py-2 align-top">
                  {a.source_entity_submitter_id ? (
                    <div className="flex flex-col">
                      <span className="font-mono text-[11px]">{a.source_entity_submitter_id}</span>
                      <span className="text-[10px] text-muted-foreground">{a.source_entity_type}</span>
                    </div>
                  ) : (
                    <span className="text-muted-foreground">—</span>
                  )}
                </td>
                <td className="px-3 py-2 align-top text-xs max-w-[22rem]">{a.notes || '—'}</td>
                <td className="px-3 py-2 align-top">
                  <div className="flex flex-col gap-0.5">
                    <span className="text-[11px]">{a.annotation_set.provider}</span>
                    <span className="text-[10px] text-muted-foreground">
                      {a.annotation_set.method === 'algorithmic' ? 'algorithmic' : 'manual'} ·{' '}
                      {a.annotation_set.origin === 'published_derived' ? 'published' : 'source'}
                    </span>
                    {a.annotation_set.source_url && (
                      <a
                        href={a.annotation_set.source_url}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center gap-1 text-[10px] text-brand underline"
                      >
                        source <ExternalLink className="h-2.5 w-2.5" />
                      </a>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="flex items-start gap-1.5 text-[11px] text-muted-foreground">
        <FileText className="h-3.5 w-3.5 shrink-0 mt-px" />
        <span>
          GDC annotations are administrative and quality-control notes about a specimen or case.
          They carry no slide coordinates and are not pathology region labels. The flag groupings
          above are a display convenience over the source’s own category values — the source itself
          does not rank them by severity.
        </span>
      </p>
    </div>
  )
}

function FilterChip({
  active,
  onClick,
  className,
  children,
}: {
  active: boolean
  onClick: () => void
  className?: string
  children: React.ReactNode
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`text-[11px] px-2 py-1 rounded-md border transition-colors ${
        active ? 'bg-brand text-white border-brand' : className || 'bg-card hover:bg-muted'
      }`}
    >
      {children}
    </button>
  )
}
